<a href="https://colab.research.google.com/github/SIYAAAA/DEEPA2/blob/master/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html


Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |████████████████████████████████| 127.3MB 52kB/s 
     |████████████████████████████████| 5.7MB 51.2MB/s 
  Found existing installation: torch 1.5.0+cu101
    Uninstalling torch-1.5.0+cu101:
      Successfully uninstalled torch-1.5.0+cu101
  Found existing installation: torchvision 0.6.0+cu101
    Uninstalling torchvision-0.6.0+cu101:
      Successfully uninstalled torchvision-0.6.0+cu101


In [0]:
import torch

In [5]:
a = torch.zeros(4,3)
print (a)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [7]:
a = torch.tensor([1,2,4.5])
type(a)
#converting list to tensor
print(a)

tensor([1.0000, 2.0000, 4.5000])


In [9]:
a = torch.zeros(4,3)
a.new_ones(6,5, dtype=torch.double)
print(a.new)

<built-in method new of Tensor object at 0x7f420c179288>


In [11]:
b=torch.rand(4,3)
b

tensor([[0.3107, 0.3626, 0.2206],
        [0.6494, 0.6384, 0.7835],
        [0.2917, 0.1905, 0.1235],
        [0.5596, 0.2596, 0.9444]])

In [12]:
a+b


tensor([[0.3107, 0.3626, 0.2206],
        [0.6494, 0.6384, 0.7835],
        [0.2917, 0.1905, 0.1235],
        [0.5596, 0.2596, 0.9444]])

In [13]:
print(torch.add(a,b))

tensor([[0.3107, 0.3626, 0.2206],
        [0.6494, 0.6384, 0.7835],
        [0.2917, 0.1905, 0.1235],
        [0.5596, 0.2596, 0.9444]])


In [0]:
result = torch.empty(4,3) #empty gives random matrix

In [17]:
torch.add(a,b,out=result)

tensor([[0.3107, 0.3626, 0.2206],
        [0.6494, 0.6384, 0.7835],
        [0.2917, 0.1905, 0.1235],
        [0.5596, 0.2596, 0.9444]])

In [18]:
b=b+a
b

tensor([[0.3107, 0.3626, 0.2206],
        [0.6494, 0.6384, 0.7835],
        [0.2917, 0.1905, 0.1235],
        [0.5596, 0.2596, 0.9444]])

In [19]:
b.add_(a)
print(b)
#reassignment operator

tensor([[0.3107, 0.3626, 0.2206],
        [0.6494, 0.6384, 0.7835],
        [0.2917, 0.1905, 0.1235],
        [0.5596, 0.2596, 0.9444]])


In [20]:
a[0][1]

tensor(0.)

In [23]:
b[:,2]

tensor([0.2206, 0.7835, 0.1235, 0.9444])

In [26]:
a =torch.randn(3,3)
a.view(9)

tensor([ 1.1389,  1.0159,  0.2040, -0.9089,  0.7655, -0.5400, -1.6247,  0.3292,
         1.3671])

In [28]:
x= torch.ones(4)#convert tensor to numpy array
y=x.numpy()
type(y)

numpy.ndarray

In [0]:
if torch.cuda.is_available():
  device = torch.torch.device("cuda")
  y = torch.ones_like(x, device = device)
  x= x.to(device)
  print(z)
#no cuda

In [0]:
#autograd finds automatic derivatives,auto gradient

In [31]:
a= torch.ones(2,2, requires_grad=True)
print(a)#track computation

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [32]:
b=a+2
b#grad_fn becoz we mentioned gradient function

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [33]:
print(b.grad_fn)

In [36]:
c = b*b*3
out = c.mean()
out

tensor(27., grad_fn=<MeanBackward0>)

In [0]:
out.backward()#prints d(out)/dx

In [38]:
print(a.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [39]:
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [41]:
import torch
import torch.nn as nn
import torch.nn.functional as F
class network(nn.Module):
  def __init__(self):
    super(network,self).__init__()
    self.conv1 = nn.Conv2d(1,6,3)
    self.conv2 = nn.Conv2d(6,16,3)# 6 features then 16 features applied
    self.fc1 = nn.Linear(16*6*6,120)#input features is 16*6*6 and 120 output features
    self.fc2 = nn.Linear(120,84)
    self.fc3 = nn.Linear(84,10)

def forward(self, x):
  x=F.max_pool2d(F.relu(self.conv1(x)),(2,2))
  x=F.max_pool2d(F.relu(self.conv2(x)),2)
  x=x.view(-1,self.num_flat_features(x))#reshape and flatten matrix
  x= F.relu(self.fc1(x))
  x= F.relu(self.fc2(x))
  x=self.fc3(x)
  return x
  #creating architecture using pytorch

def num_flat_features(self,x):
  size= x.size()[1:]
  num_features = 1
  for s in size:
    num_features*=s
  return num_features

net = network()
print(net)
#loss and optimizer re not here so cannot backpropagate

s=list(net.parameters())

network(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)
