<a href="https://colab.research.google.com/github/SIYAAAA/DEEPA2/blob/master/tf2.x.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow==2.0.0

     |████████████████████████████████| 86.3MB 65kB/s 
     |████████████████████████████████| 450kB 42.4MB/s 
     |████████████████████████████████| 3.8MB 44.3MB/s 
  Created wheel for gast: filename=gast-0.2.2-cp36-none-any.whl size=7540 sha256=b20b2bf5ed39e19e901905fea96b09fd14241ba030108246c07fca45a9f1b279
  Stored in directory: /root/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
Successfully built gast
ERROR: tensorflow-probability 0.10.0 has requirement gast>=0.3.2, but you'll have gast 0.2.2 which is incompatible.
  Found existing installation: gast 0.3.3
    Uninstalling gast-0.3.3:
      Successfully uninstalled gast-0.3.3
  Found existing installation: tensorflow-estimator 2.2.0
    Uninstalling tensorflow-estimator-2.2.0:
      Successfully uninstalled tensorflow-estimator-2.2.0
  Found existing installation: tensorboard 2.2.2
    Uninstalling tensorboard-2.2.2:
      Successfully uninstalled tensorboard-2.2.2
  Found existing installation: t

In [3]:
import tensorflow as tf
neuron = tf.constant(42)
neuron
#tf 2.x has resolved version issues


<tf.Tensor: id=0, shape=(), dtype=int32, numpy=42>

In [5]:
x= tf.constant([[4,2],[9,5]])
x

<tf.Tensor: id=1, shape=(2, 2), dtype=int32, numpy=
array([[4, 2],
       [9, 5]], dtype=int32)>

In [6]:
con1=tf.constant([[3,4,5],[3,4,6]])
con2=tf.constant([[1,2,3],[3,4,5]])
y=tf.add(con1,con2)
y
#index wise add
#backend tf and pytorch use numpy

<tf.Tensor: id=4, shape=(2, 3), dtype=int32, numpy=
array([[ 4,  6,  8],
       [ 6,  8, 11]], dtype=int32)>

In [7]:
tf.random.normal(shape=(2,2),mean=0,stddev=1.0)

<tf.Tensor: id=10, shape=(2, 2), dtype=float32, numpy=
array([[ 0.516382  ,  0.607438  ],
       [-0.57156175, -1.4941229 ]], dtype=float32)>

In [9]:
tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int32)#gives random data between 0-10

<tf.Tensor: id=17, shape=(2, 2), dtype=int32, numpy=
array([[7, 3],
       [8, 4]], dtype=int32)>

In [15]:
var=tf.Variable(98)
var

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=98>

In [12]:
n=tf.constant(1)
n

<tf.Tensor: id=27, shape=(), dtype=int32, numpy=1>

In [16]:
var.assign(54.)#keep data type same

TypeError: ignored

In [14]:
n.assign(54)
#non changeable with variable

AttributeError: ignored

In [27]:
tensor=tf.Variable([[[11,12,13],[10,23,34]],[[45,46,67],[1,2,3]]])
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[11, 12, 13],
        [10, 23, 34]],

       [[45, 46, 67],
        [ 1,  2,  3]]], dtype=int32)>

In [18]:
t2=tf.reshape(tensor,[3,2])
t2


<tf.Tensor: id=49, shape=(3, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 10],
       [23, 34]], dtype=int32)>

In [0]:
#question dismissed from session for not relevant

In [23]:
tf.rank(tensor)

<tf.Tensor: id=69, shape=(), dtype=int32, numpy=3>

In [25]:
t1 = tensor[1,0,2]
t1
#46 will be answer

<tf.Tensor: id=79, shape=(), dtype=int32, numpy=67>

In [26]:
print(tensor.numpy)

<bound method BaseResourceVariable.numpy of <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[11, 12, 13],
        [10, 23, 34]],

       [[45, 45, 67],
        [ 1,  2,  3]]], dtype=int32)>>


In [29]:
m1=tf.Variable([[11,2,3]])
m2=tf.Variable([[1,4,5]])
tf.matmul(m1,tf.transpose(a=m2))
#imported functions from numpy

<tf.Tensor: id=125, shape=(1, 1), dtype=int32, numpy=array([[34]], dtype=int32)>

In [30]:
i=tf.cast(tensor,dtype=tf.float32)
i

<tf.Tensor: id=127, shape=(2, 2, 3), dtype=float32, numpy=
array([[[11., 12., 13.],
        [10., 23., 34.]],

       [[45., 46., 67.],
        [ 1.,  2.,  3.]]], dtype=float32)>

In [33]:
tf.random.set_seed(11)
tf.random.uniform(shape=(2,4))
#seed does not let values change

<tf.Tensor: id=141, shape=(2, 4), dtype=float32, numpy=
array([[0.25061703, 0.8159225 , 0.29261577, 0.9327979 ],
       [0.76441216, 0.14772058, 0.33168125, 0.00725472]], dtype=float32)>

In [34]:
tf.argmax(input=tensor)

<tf.Tensor: id=144, shape=(2, 3), dtype=int64, numpy=
array([[1, 1, 1],
       [0, 0, 0]])>

In [0]:
#checkpointin physical file stores weights z

In [37]:
var1=tf.Variable([[5,6,9,3],[4,5,6,7]])
checkpoint=tf.train.Checkpoint(var=var1)
savepath = checkpoint.save(r'C:\Users\kumar\Desktop\ckpt')
var1.assign([[0,0,9,8],[2,3,4,5]])


<tf.Variable 'UnreadVariable' shape=(2, 4) dtype=int32, numpy=
array([[0, 0, 9, 8],
       [2, 3, 4, 5]], dtype=int32)>

In [0]:
def f1(x,y):
  return tf.reduce_mean(input_tensor=tf.multiply(x**3,6))

In [38]:
a=tf.random.normal(shape=(2,2))
b=tf.random.normal(shape=(2,2))
with tf.GradientTape() as tape:
  tape.watch(a)#will keep on finding derivative,stores in memory for gradient of last time without watch it will not change values
  c=tf.sqrt(tf.square(a)+tf.square(b))
  dc_da = tape.gradient(c,a)#dc/da
  print(dc_da)

tf.Tensor(
[[ 0.4063939  0.6648737]
 [-0.9829512 -0.6326042]], shape=(2, 2), dtype=float32)


In [39]:
mnist_data = tf.keras.datasets.mnist
(train_x,train_y),(test_x,test_y)=mnist_data.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [0]:
epochs=10
batch_size = 32
train_x,test_x=tf.cast(train_x/255.0,tf.float32),tf.cast(test_x/255.0,tf.float32)
train_y,test_y=tf.cast(train_y,tf.int64),tf.cast(test_y,tf.int64)

In [48]:
mnistmodel1=tf.keras.models.Sequential([tf.keras.layers.Flatten(),tf.keras.layers.Dense(512,activation=tf.nn.relu),
                                        tf.keras.layers.Dropout(0.2),
                                        tf.keras.layers.Dense(10,activation=tf.nn.softmax)])
optimiser=tf.keras.optimizers.Adam()#dropout creates randomization
mnistmodel1.compile(optimizer=optimiser,loss='sparse_categorical_crossentropy', metrics = ['accuracy'])
mnistmodel1.fit(train_x,train_y,batch_size=32,epochs=5)
#loss decresing and accuracy increasing

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 9s 151us/sample - loss: 0.8807 - accuracy: 0.7796
Epoch 2/5
60000/60000 [==============================] - 8s 140us/sample - loss: 0.3833 - accuracy: 0.8922
Epoch 3/5
60000/60000 [==============================] - 9s 142us/sample - loss: 0.3232 - accuracy: 0.9078
Epoch 4/5
60000/60000 [==============================] - 8s 141us/sample - loss: 0.2898 - accuracy: 0.9150
Epoch 5/5
60000/60000 [==============================] - 8s 140us/sample - loss: 0.2640 - accuracy: 0.9235


In [49]:
mnistmodel1.predict_classes([test_x])

array([7, 2, 1, ..., 4, 5, 6])

In [50]:
mnistmodel1.predict(test_x)

array([[8.0383208e-05, 6.8300501e-08, 2.1994489e-04, ..., 9.9661344e-01,
        1.4002811e-05, 1.1047217e-03],
       [8.0226653e-04, 3.4392760e-05, 9.7070932e-01, ..., 2.1949440e-09,
        2.1513782e-03, 7.4627557e-09],
       [2.8112288e-06, 9.8514646e-01, 4.7682477e-03, ..., 3.1956374e-03,
        1.8123805e-03, 4.7426872e-04],
       ...,
       [1.3213619e-07, 9.0514072e-07, 8.8211355e-06, ..., 5.7487388e-04,
        5.2447445e-03, 3.4193084e-02],
       [2.9956110e-04, 2.1471469e-04, 3.7924594e-05, ..., 5.5099317e-06,
        1.0607711e-01, 6.9656016e-05],
       [1.0394812e-04, 4.1272902e-10, 4.2927885e-04, ..., 1.9385746e-09,
        2.3060204e-06, 1.2952903e-07]], dtype=float32)

In [51]:
test_x

<tf.Tensor: id=214, shape=(10000, 28, 28), dtype=float32, numpy=
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
      

In [54]:
tf.saved_model.save(
    mnistmodel1,export_dir, signatures=None, options=None
)

NameError: ignored